config/routes.rb
Rails.application.routes.draw do
  get 'client/home'

  get 'client/projects'

  get 'client/status'

  get 'client/milestones'

  get 'client/quotes'

  get 'client/support'

  get 'client/tickets'

  # set the index page
  root 'pages#home'

  get 'pages/about'

  get 'pages/home'

  get 'pages/contact'

  get 'pages/portfolio'

  get 'pages/services'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = "About Us - Reaper Studios"
  end

  def home
    @title = "Reaper Studios"
  end

  def contact
      @title = "Contact Us - Reaper Studios"
  end

  def services
      @title = "Services - Reaper Studios"
  end

  def portfolio
      @title = "Portfolio - Reaper Studios"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title><%= @title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Krona+One' %>
    <%= stylesheet_link_tag 'application', 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <p class='skipnavigation'><a href="#contentstart">Skip Navigation</a></p>
    <div id='container'>
      <header>
        <nav id='nav' class='topnav'>
          <span>
            <%= image_tag('reaper_logo.png', :id=> 'header-logo') %>
          </span>
          <ul>
            <li id='mobileMenu'><a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a></li>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", pages_about_path %></li>
            <li><%= link_to "Get a Quote", pages_contact_path %></li>
            <li><%= link_to "Services", pages_services_path %></li>
            <li><%= link_to "Portfolio", pages_portfolio_path %></li>
            <li><%= link_to "Contact Us", pages_contact_path %></li>
          </ul>
        </nav>
        <nav id='nav' class='topnav-full'>
            <ul class='float-left'>
              <li id='mobileMenu'><a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a></li>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", pages_about_path %></li>
              <li><%= link_to "Get a Quote", pages_contact_path %></li>
            </ul>
            <%= image_tag('reaper_logo.png', :id => 'header-logo-full') %>
            <ul class='float-right'>
              <li><%= link_to "Services", pages_services_path %></li>
              <li><%= link_to "Portfolio", pages_portfolio_path %></li>
              <li><%= link_to "Contact Us", pages_contact_path %></li>
            </ul>
        </nav>
      </header>
      <div id='body'>
        <%= yield %>
      </div>
      <footer>
        <p>This is the footer</p>
      </footer>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<section>
  <h2>About Us</h2>
  <article>
  <p>Reaper Studios was founded in March 2017 by Brian Heller and Nathan Barr. Brian and Nathan had served together in the military previously, Brian in the Marine Corps and Nathan in the Navy, and deployed to Afghanistan in 2010 with the callsign
    “Reaper.”  After separating from the military, their love for video games helped them to keep in touch over the years. Feeling generally undervalued and unchallenged at their respective “day jobs,” Brian and Nathan decided to undertake a new adventure. This
    new adventure would include ties to the online and mobile gaming communities and challenge them to be their best for the benefit of the user. This entity would be titled Reaper Studios to embrace their past as they forge a path toward their future.</p>
  </article>
</section>
<section>

  <h2>Our Team</h2>
  <article class='col-3 aboutus'>
    <h3>Nathan Barr</h3>
    <a href="https://www.linkedin.com/in/nathan-barr-03a3634a/">
      <%= image_tag("NathanBarr.jpg", :class=> 'circular-img') %>
    </a>
    <h4>Co-Founder & CEO</h4>

  </article>
  <article class='col-3 aboutus'>
    <h3>Jesse Duncan</h3>
    <a href="https://www.linkedin.com/in/brian-heller-ab469892/">
      <%= image_tag("JesseDuncan.jpg", :class=> 'circular-img') %>
    </a>
    <h4>Co-Founder & COO</h4>
  </article>
  <article class='col-3 aboutus'>
  <h3>Brian Heller</h3>
    <a href="https://www.linkedin.com/in/brian-heller-ab469892/">
      <%= image_tag("BrianHeller.jpg", :class=> 'circular-img') %>
    </a>
    <h4>Co-Founder & CTO</h4>
  </article>
</section>
<section>
  <article class='col-2 left align-center aboutus'>
    <h3>Brittany Heller</h3>
    <a href="https://www.linkedin.com/in/brittany-heller-b1402964/">
      <%= image_tag("BrittanyHeller.jpg", :class=> 'circular-img') %>
    </a>
    <h4>Software Developer</h4>
  </article>
  <article class='col-2 right align-center aboutus'>
  <h3>Zak Reeves</h3>
  <a href="https://www.linkedin.com/in/zachary-reeves-177754a7/">
      <%= image_tag("ZakReeves.jpg", :class=> 'circular-img') %>
    </a>
      <h4>Marketing and Sales Guru</h4>
  </article>
</section>

</section>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<section id='services' class='col'>
  <h2>Services</h2>
  <article class='col-3'>
    <figure>
      <%= image_tag("fingerprint.svg", size: "150") %>
      <figcaption>Branding</figcaption>
    </figure>
  </article>
  <article class='col-3'>
    <figure>
      <%= image_tag("list.svg", size: "150") %>
      <figcaption>Consulting</figcaption>
    </figure>

  </article>
  <article class='col-3'>
    <figure>
      <%= image_tag("magic-wand.svg", size: "150") %>
      <figcaption>Development</figcaption>
    </figure>
  </article>
</section>
<section class='col row-75'>
  <h2>Why Choose Reaper Studios</h2>
  <article class='col-2 left row-auto'>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et eleifend tortor. Vestibulum in porttitor nulla. Suspendisse ut quam quis mi vestibulum ultricies. Ut vel nulla lectus. Curabitur tincidunt nisl sit amet vulputate ullamcorper. Sed eget
    risus interdum, fermentum ante et, lobortis enim. Phasellus fermentum congue vehicula. Mauris aliquet ligula pretium risus venenatis laoreet. Nam cursus convallis convallis. Nunc elementum neque mollis, varius nisi in, pharetra erat. Maecenas iaculis
    interdum aliquam. Donec id enim eu orci vehicula mollis in vel metus. Vestibulum hendrerit pharetra quam
  </article>
  <article class='col-2 right row-auto'>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et eleifend tortor. Vestibulum in porttitor nulla. Suspendisse ut quam quis mi vestibulum ultricies. Ut vel nulla lectus. Curabitur tincidunt nisl sit amet vulputate ullamcorper. Sed eget
    risus interdum, fermentum ante et, lobortis enim. Phasellus fermentum congue vehicula. Mauris aliquet ligula pretium risus venenatis laoreet. Nam cursus convallis convallis. Nunc elementum neque mollis, varius nisi in, pharetra erat. Maecenas iaculis
    interdum aliquam. Donec id enim eu orci vehicula mollis in vel metus. Vestibulum hendrerit pharetra quamLorem ipsum dolor sit amet, consectetur adipiscing elit. In et eleifend tortor. Vestibulum in porttitor nulla. Suspendisse ut quam quis mi
    vestibulum ultricies. Ut vel nulla lectus. Curabitur tincidunt nisl sit amet vulputate ullamcorper. Sed eget risus interdum, fermentum ante et, lobortis enim. Phasellus fermentum congue vehicula. Mauris aliquet ligula pretium risus venenatis laoreet.
    Nam cursus convallis convallis. Nunc elementum neque mollis, varius nisi in, pharetra erat. Maecenas iaculis interdum aliquam. Donec id enim eu orci vehicula mollis in vel metus. Vestibulum hendrerit pharetra quamLorem ipsum dolor sit amet,
    consectetur adipiscing elit. In et eleifend tortor. Vestibulum in porttitor nulla. Suspendisse ut quam quis mi vestibulum ultricies. Ut vel nulla lectus. Curabitur tincidunt nisl sit amet vulputate ullamcorper. Sed eget risus interdum, fermentum ante
    et, lobortis enim. Phasellus fermentum congue vehicula. Mauris aliquet ligula pretium risus venenatis laoreet. Nam cursus convallis convallis. Nunc elementum neque mollis, varius nisi in, pharetra erat. Maecenas iaculis interdum aliquam.
  </article>
</section>

app/views/pages/portfolio.html.erb
<section>
  <h1>Portfolio</h1>
  <article>
      <p>Project information</p>
  </article>
</section>

app/views/pages/services.html.erb
<section class='col wrap'>
  <h1>Services</h1>
    <article class='left'>
      <figure>
        <%= image_tag("fingerprint.svg", size: "150") %>
        <figcaption>Branding</figcaption>
      </figure>
      <p>Let us help you develop your brand.</p>
    </article>
    <article class='center'>
      <figure>
        <%= image_tag("magic-wand.svg", size: "150") %>
        <figcaption>Development</figcaption>
      </figure>
      <p>Bring your projects to life.</p>
    </article>
    <article class='right'>
      <figure>
        <%= image_tag("list.svg", size: "150") %>
        <figcaption>Consulting</figcaption>
      </figure>
      <p>Get your questions answered.</p>
    </article>
</section>